"use client";
/* Product media is transformed by Cloudinary before these URLs are stored. */
/* eslint-disable @next/next/no-img-element */

import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BellRing, Check, ChefHat, ChevronRight, CircleMinus, CirclePlus, Clock3, Minus, Plus, Search, ShoppingBag, Sparkles, Users, Utensils, X } from "lucide-react";
import { toast } from "sonner";
import { api, elapsed, money } from "@/lib/client-api";
import { Badge, Button, EmptyState, Input, PageHeader, Skeleton } from "@/components/ui";
import { cn } from "@/lib/utils";

type OrderItem = { id: string; productName: string; quantity: number; unitPrice: string; total: string; status: string; notes?: string | null; modifiers?: Array<{ name: string; priceDelta: string }> };
type ActiveOrder = { id: string; number: number; status: string; total: string; sentAt?: string | null; waiter?: { firstName: string } | null; items: OrderItem[] };
type Table = { id: string; number: number; capacity: number; status: string; orders: ActiveOrder[]; tableSessions: Array<{ openedAt: string; guestCount: number }> };
type Zone = { id: string; name: string; tables: Table[] };
type Modifier = { name: string; priceDelta: string };
type Product = { id: string; name: string; description?: string | null; price: string; imageUrl?: string | null; estimatedMinutes?: number | null; availability: string; category: { id: string; name: string }; variants: Array<Modifier & { id: string; groupName: string }>; addons: Array<{ id: string; name: string; price: string }> };
type ProductData = { products: Product[]; categories: Array<{ id: string; name: string }>; stations: unknown[] };
type CartItem = { key: string; product: Product; quantity: number; notes: string; modifiers: Array<{ name: string; priceDelta: number }> };

const tableTone: Record<string, "success" | "warning" | "danger" | "info" | "purple" | "neutral"> = { FREE: "success", RESERVED: "purple", SENT: "info", PREPARING: "warning", PARTIALLY_READY: "warning", READY: "success", WAITING_DELIVERY: "success", WAITING_BILL: "purple", PENDING_PAYMENT: "danger", OCCUPIED: "info" };
const labels: Record<string, string> = { FREE: "Disponible", RESERVED: "Reservada", SENT: "En cocina", PREPARING: "Preparando", PARTIALLY_READY: "Parcialmente listo", READY: "Listo para entregar", WAITING_DELIVERY: "Esperando entrega", WAITING_BILL: "Solicitó cuenta", PENDING_PAYMENT: "Pendiente de pago", OCCUPIED: "Ocupada", DELIVERED: "Entregado" };

export default function TablesPage() {
  const client = useQueryClient(); const searchRef = useRef<HTMLInputElement>(null);
  const { data: zones, isLoading } = useQuery({ queryKey: ["tables"], queryFn: () => api<Zone[]>("/api/tables") });
  const { data: menu } = useQuery({ queryKey: ["products"], queryFn: () => api<ProductData>("/api/products?available=true") });
  const [zoneId, setZoneId] = useState<string>(""); const [selected, setSelected] = useState<Table | null>(null); const [category, setCategory] = useState("all"); const [search, setSearch] = useState(""); const [guests, setGuests] = useState(2); const [cart, setCart] = useState<CartItem[]>([]); const [customize, setCustomize] = useState<Product | null>(null);
  const currentZone = zones?.find(zone => zone.id === zoneId) ?? zones?.[0];
  const visible = useMemo(() => menu?.products.filter(product => (category === "all" || product.category.id === category) && `${product.name} ${product.category.name}`.toLowerCase().includes(search.toLowerCase())) ?? [], [menu, category, search]);
  const total = cart.reduce((sum, item) => sum + (Number(item.product.price) + item.modifiers.reduce((acc, modifier) => acc + modifier.priceDelta, 0)) * item.quantity, 0);
  const addQuick = (product: Product) => setCart(items => { const existing = items.find(item => item.product.id === product.id && !item.modifiers.length && !item.notes); return existing ? items.map(item => item.key === existing.key ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { key: crypto.randomUUID(), product, quantity: 1, notes: "", modifiers: [] }]; });
  const changeQuantity = (key: string, change: number) => setCart(items => items.map(item => item.key === key ? { ...item, quantity: item.quantity + change } : item).filter(item => item.quantity > 0));
  const submitOrder = useMutation({
    mutationFn: () => api<ActiveOrder>("/api/orders", { method: "POST", body: JSON.stringify({ idempotencyKey: crypto.randomUUID(), tableId: selected!.id, guestCount: guests, items: cart.map(item => ({ productId: item.product.id, quantity: item.quantity, notes: item.notes || undefined, modifiers: item.modifiers })) }) }),
    onSuccess: order => { toast.success(`Pedido #${order.number} enviado a cocina.`); setCart([]); void client.invalidateQueries({ queryKey: ["tables"] }); void client.invalidateQueries({ queryKey: ["orders"] }); setSelected(null); },
    onError: error => toast.error(error.message)
  });
  const action = useMutation({
    mutationFn: ({ orderId, action }: { orderId: string; action: string }) => api(`/api/orders/${orderId}/status`, { method: "PATCH", body: JSON.stringify({ action }) }),
    onSuccess: (_data, variables) => { toast.success(variables.action === "deliver" ? "Pedido entregado." : "Cuenta enviada a caja."); void client.invalidateQueries({ queryKey: ["tables"] }); setSelected(null); }, onError: error => toast.error(error.message)
  });
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "F2") { event.preventDefault(); searchRef.current?.focus(); } if (event.key === "F4" && selected && cart.length) { event.preventDefault(); submitOrder.mutate(); } if (event.key === "Escape") setSelected(null); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [selected, cart.length, submitOrder]);

  if (isLoading) return <div className="page-stack"><PageHeader title="Salón y mesas"/><div className="table-grid">{Array.from({ length: 12 }).map((_, i) => <Skeleton className="h-48 rounded-3xl" key={i}/>)}</div></div>;
  return <div className="page-stack tables-page"><PageHeader eyebrow="SALÓN EN VIVO" title="Salón y mesas" description="Detecta de un vistazo dónde te necesitan." action={<div className="legend"><span><i className="free"/> Disponible</span><span><i className="busy"/> En atención</span><span><i className="ready"/> Necesita acción</span></div>}/><div className="zone-tabs">{zones?.map(zone => <button key={zone.id} onClick={() => setZoneId(zone.id)} className={zone.id === currentZone?.id ? "active" : ""}>{zone.name}<span>{zone.tables.length}</span></button>)}</div><section className="table-grid">{currentZone?.tables.map(table => { const order = table.orders[0]; const minutes = table.tableSessions[0] ? elapsed(table.tableSessions[0].openedAt) : 0; const ready = order?.items.filter(item => item.status === "READY").length ?? 0; return <button key={table.id} className={cn("table-card", `table-${table.status.toLowerCase()}`)} onClick={() => { setSelected(table); setGuests(table.tableSessions[0]?.guestCount ?? Math.min(2, table.capacity)); }}><div className="table-card-top"><span>MESA</span><Badge tone={tableTone[table.status] ?? "neutral"}>{labels[table.status] ?? table.status}</Badge></div><strong>{String(table.number).padStart(2, "0")}</strong>{table.status === "FREE" ? <div className="table-free-detail"><Users size={18}/><span>Hasta {table.capacity} personas</span><small>Toca para abrir</small></div> : <div className="table-busy-detail"><div><Clock3 size={16}/>{minutes} min</div><div><Users size={16}/>{table.tableSessions[0]?.guestCount ?? "—"}</div><p>{order?.waiter?.firstName ?? "Equipo"}</p>{order && <b>{money(order.total)}</b>}{order?.status === "PARTIALLY_READY" && <small>{ready}/{order.items.length} listos</small>}</div>}<span className="table-arrow"><ChevronRight size={18}/></span></button>; })}</section>
    {!currentZone?.tables.length && <EmptyState icon={<Utensils/>} title="No hay mesas en esta zona" detail="Configura las mesas desde administración."/>}
    {selected && <div className="order-overlay"><section className="order-workspace"><header className="order-workspace-header"><button className="icon-button" onClick={() => setSelected(null)}><ArrowLeft/></button><div><span>NUEVO PEDIDO</span><h2>Mesa {String(selected.number).padStart(2, "0")}</h2></div><div className="guest-stepper"><Users size={18}/><button onClick={() => setGuests(Math.max(1, guests - 1))}><Minus/></button><strong>{guests}</strong><button onClick={() => setGuests(Math.min(50, guests + 1))}><Plus/></button><span>personas</span></div><button className="icon-button order-close" onClick={() => setSelected(null)}><X/></button></header>
      <div className="order-workspace-body"><div className="menu-pane"><div className="menu-toolbar"><div className="search-field"><Search size={18}/><Input ref={searchRef} value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar platos... (F2)"/></div><Badge tone="success"><span className="live-dot"/> Menú actualizado</Badge></div><div className="category-pills"><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>Todo</button>{menu?.categories.map(item => <button key={item.id} className={category === item.id ? "active" : ""} onClick={() => setCategory(item.id)}>{item.name}</button>)}</div><div className="product-grid">{visible.map(product => <article className="product-card" key={product.id}><button className="product-main" onClick={() => setCustomize(product)}>{product.imageUrl ? <img src={product.imageUrl} alt=""/> : <div className="product-placeholder"><Utensils/></div>}<div><span>{product.category.name}</span><h3>{product.name}</h3><p>{product.description}</p><small><Clock3 size={13}/>{product.estimatedMinutes ?? 10} min</small></div></button><footer><strong>{money(product.price)}</strong><button onClick={() => addQuick(product)} aria-label={`Agregar ${product.name}`}><Plus size={21}/></button></footer></article>)}</div></div>
        <aside className="cart-pane"><div className="cart-heading"><div><ShoppingBag/><span>{cart.reduce((sum, item) => sum + item.quantity, 0)}</span></div><h3>Tu pedido</h3><p>Mesa {String(selected.number).padStart(2, "0")}</p></div>{selected.orders[0] && <div className="existing-order"><div><ChefHat/><span><strong>Pedido #{selected.orders[0].number}</strong><small>{labels[selected.orders[0].status] ?? selected.orders[0].status}</small></span></div><strong>{money(selected.orders[0].total)}</strong>{selected.orders[0].status === "READY" && <Button onClick={() => action.mutate({ orderId: selected.orders[0].id, action: "deliver" })}><Check/> Entregar ahora</Button>}{selected.orders[0].status === "DELIVERED" && <Button onClick={() => action.mutate({ orderId: selected.orders[0].id, action: "request_bill" })}><BellRing/> Solicitar cuenta</Button>}</div>}{!cart.length ? <EmptyState icon={<ShoppingBag/>} title="El pedido está vacío" detail="Toca + para agregar platos rápidamente."/> : <div className="cart-items">{cart.map(item => <div className="cart-item" key={item.key}><div><strong>{item.product.name}</strong>{item.modifiers.map(modifier => <small key={modifier.name}>+ {modifier.name}</small>)}{item.notes && <small>{item.notes}</small>}<span>{money((Number(item.product.price) + item.modifiers.reduce((sum, modifier) => sum + modifier.priceDelta, 0)) * item.quantity)}</span></div><div className="quantity"><button onClick={() => changeQuantity(item.key, -1)}><CircleMinus/></button><strong>{item.quantity}</strong><button onClick={() => changeQuantity(item.key, 1)}><CirclePlus/></button></div></div>)}</div>}<div className="cart-total"><div><span>Subtotal</span><strong>{money(total)}</strong></div><div className="grand-total"><span>Total</span><strong>{money(total)}</strong></div><Button className="send-order" loading={submitOrder.isPending} disabled={!cart.length} onClick={() => submitOrder.mutate()}><ChefHat/> {submitOrder.isPending ? "Enviando..." : "Enviar a cocina"}<kbd>F4</kbd></Button><small><Sparkles size={13}/> Cocina lo recibirá al instante</small></div></aside></div></section></div>}
    {customize && <ProductCustomizer product={customize} onClose={() => setCustomize(null)} onAdd={item => { setCart(items => [...items, item]); setCustomize(null); toast.success(`${customize.name} agregado.`); }}/>}</div>;
}

function ProductCustomizer({ product, onClose, onAdd }: { product: Product; onClose: () => void; onAdd: (item: CartItem) => void }) {
  const [quantity, setQuantity] = useState(1); const [variant, setVariant] = useState<Modifier | null>(null); const [addons, setAddons] = useState<Array<{ name: string; price: string }>>([]); const [notes, setNotes] = useState("");
  const groups = [...new Set(product.variants.map(item => item.groupName))];
  const toggleAddon = (addon: { name: string; price: string }) => setAddons(items => items.some(item => item.name === addon.name) ? items.filter(item => item.name !== addon.name) : [...items, addon]);
  const modifiers = [...(variant ? [{ name: variant.name, priceDelta: Number(variant.priceDelta) }] : []), ...addons.map(item => ({ name: item.name, priceDelta: Number(item.price) }))];
  const total = (Number(product.price) + modifiers.reduce((sum, item) => sum + item.priceDelta, 0)) * quantity;
  return <div className="dialog-backdrop" onMouseDown={onClose}><div className="customizer" onMouseDown={e => e.stopPropagation()}><button className="icon-button customizer-close" onClick={onClose}><X/></button>{product.imageUrl && <img className="customizer-image" src={product.imageUrl} alt=""/>}<div className="customizer-content"><p className="eyebrow">PERSONALIZA TU PEDIDO</p><h2>{product.name}</h2><p>{product.description}</p>{groups.map(group => <div className="option-group" key={group}><strong>{group}</strong><small>Elige una opción</small>{product.variants.filter(item => item.groupName === group).map(item => <label key={item.id}><input type="radio" name={group} checked={variant?.name === item.name} onChange={() => setVariant(item)}/><span>{item.name}</span>{Number(item.priceDelta) > 0 && <b>+ {money(item.priceDelta)}</b>}</label>)}</div>)}{!!product.addons.length && <div className="option-group"><strong>Extras</strong><small>Opcional</small>{product.addons.map(item => <label key={item.id}><input type="checkbox" checked={addons.some(addon => addon.name === item.name)} onChange={() => toggleAddon(item)}/><span>{item.name}</span><b>+ {money(item.price)}</b></label>)}</div>}<label className="notes-field">Observaciones<textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ej. sin cebolla, salsa aparte..." maxLength={300}/></label></div><footer><div className="quantity large"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus/></button><strong>{quantity}</strong><button onClick={() => setQuantity(quantity + 1)}><Plus/></button></div><Button onClick={() => onAdd({ key: crypto.randomUUID(), product, quantity, notes, modifiers })}>Agregar · {money(total)}</Button></footer></div></div>;
}
