"use client";
/* Product media is transformed by Cloudinary before these URLs are stored. */
/* eslint-disable @next/next/no-img-element */

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clock3, ImagePlus, MoreHorizontal, PackageCheck, Plus, Search, Sparkles, UploadCloud, Utensils, X } from "lucide-react";
import { toast } from "sonner";
import { api, money } from "@/lib/client-api";
import { Badge, Button, EmptyState, Input, PageHeader, Skeleton } from "@/components/ui";

type Product = { id: string; name: string; slug: string; description?: string; price: string; cost: string; imageUrl?: string; imagePublicId?: string; estimatedMinutes?: number; availability: "AVAILABLE" | "LOW_STOCK" | "SOLD_OUT" | "TEMPORARILY_UNAVAILABLE"; category: { id: string; name: string }; station?: { id: string; name: string } };
type Data = { products: Product[]; categories: Array<{ id: string; name: string }>; stations: Array<{ id: string; name: string }> };
const availability = [{ id: "AVAILABLE", label: "Disponible", tone: "success" }, { id: "LOW_STOCK", label: "Poco stock", tone: "warning" }, { id: "SOLD_OUT", label: "Agotado", tone: "danger" }, { id: "TEMPORARILY_UNAVAILABLE", label: "No disponible", tone: "neutral" }] as const;

export default function ProductsPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(""); const [category, setCategory] = useState("all"); const [createOpen, setCreateOpen] = useState(false); const [editingAvailability, setEditingAvailability] = useState<string | null>(null);
  const { data, isLoading } = useQuery({ queryKey: ["products"], queryFn: () => api<Data>("/api/products") });
  const products = useMemo(() => data?.products.filter(product => (category === "all" || product.category.id === category) && product.name.toLowerCase().includes(search.toLowerCase())) ?? [], [data, search, category]);
  const update = useMutation({ mutationFn: ({ id, value }: { id: string; value: string }) => api(`/api/products/${id}`, { method: "PATCH", body: JSON.stringify({ availability: value }) }), onMutate: ({ id, value }) => { client.setQueryData<Data>(["products"], current => current ? { ...current, products: current.products.map(product => product.id === id ? { ...product, availability: value as Product["availability"] } : product) } : current); }, onSuccess: () => { toast.success("Disponibilidad actualizada en todos los dispositivos."); setEditingAvailability(null); }, onError: error => { toast.error(error.message); void client.invalidateQueries({ queryKey: ["products"] }); } });
  if (isLoading) return <div><PageHeader title="Productos y menú"/><div className="product-admin-grid">{Array.from({ length: 8 }).map((_, i) => <Skeleton className="h-80 rounded-3xl" key={i}/>)}</div></div>;
  return <div className="page-stack"><PageHeader eyebrow="MENÚ CENTRAL" title="Productos y menú" description="Precios y disponibilidad sincronizados al instante." action={<Button onClick={() => setCreateOpen(true)}><Plus/> Nuevo producto</Button>}/><section className="catalog-summary"><div><PackageCheck/><span><strong>{data?.products.filter(p => p.availability === "AVAILABLE").length}</strong> disponibles</span></div><div><Clock3/><span><strong>{data?.products.filter(p => p.availability === "LOW_STOCK").length}</strong> con poco stock</span></div><div><Utensils/><span><strong>{data?.products.filter(p => p.availability === "SOLD_OUT").length}</strong> agotados</span></div><p><Sparkles/> Los cambios aparecen en salón y menú QR sin recargar.</p></section><div className="catalog-toolbar"><div className="search-field"><Search/><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar producto..."/></div><div className="category-pills"><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>Todos</button>{data?.categories.map(item => <button key={item.id} className={category === item.id ? "active" : ""} onClick={() => setCategory(item.id)}>{item.name}</button>)}</div></div><section className="product-admin-grid">{products.map(product => { const state = availability.find(item => item.id === product.availability)!; return <article key={product.id}><div className="admin-product-image">{product.imageUrl ? <img src={product.imageUrl} alt=""/> : <Utensils/>}<Badge tone={state.tone}>{state.label}</Badge><button><MoreHorizontal/></button></div><div className="admin-product-body"><span>{product.category.name} · {product.station?.name ?? "Sin estación"}</span><h3>{product.name}</h3><p>{product.description}</p><div><strong>{money(product.price)}</strong><small><Clock3/> {product.estimatedMinutes ?? 10} min</small></div><button className="availability-button" onClick={() => setEditingAvailability(editingAvailability === product.id ? null : product.id)}><i className={`state-${product.availability.toLowerCase()}`}/>{state.label}<MoreHorizontal/></button>{editingAvailability === product.id && <div className="availability-menu">{availability.map(item => <button key={item.id} onClick={() => update.mutate({ id: product.id, value: item.id })}><i className={`state-${item.id.toLowerCase()}`}/><span>{item.label}</span>{product.availability === item.id && <Check/>}</button>)}</div>}</div></article>; })}</section>{!products.length && <EmptyState icon={<Utensils/>} title="Sin resultados" detail="Prueba con otra categoría o término."/>}{createOpen && data && <CreateProduct data={data} onClose={() => setCreateOpen(false)} onCreated={() => { setCreateOpen(false); void client.invalidateQueries({ queryKey: ["products"] }); }}/>}</div>;
}

function CreateProduct({ data, onClose, onCreated }: { data: Data; onClose: () => void; onCreated: () => void }) {
  const [form, setForm] = useState({ name: "", price: 0, cost: 0, estimatedMinutes: 15, categoryId: data.categories[0]?.id ?? "", stationId: data.stations[0]?.id ?? "", description: "", imageUrl: "", imagePublicId: "" }); const [uploading, setUploading] = useState(false);
  const create = useMutation({ mutationFn: () => api("/api/products", { method: "POST", body: JSON.stringify({ ...form, slug: form.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), imageUrl: form.imageUrl || undefined, imagePublicId: form.imagePublicId || undefined }) }), onSuccess: () => { toast.success("Producto creado y publicado."); onCreated(); }, onError: error => toast.error(error.message) });
  const upload = async (file: File) => { setUploading(true); try { const signature = await api<{ cloudName: string; apiKey: string; timestamp: number; folder: string; signature: string }>("/api/storage/signature", { method: "POST", body: JSON.stringify({ folder: "products" }) }); const body = new FormData(); body.append("file", file); body.append("api_key", signature.apiKey); body.append("timestamp", String(signature.timestamp)); body.append("folder", signature.folder); body.append("signature", signature.signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/image/upload`, { method: "POST", body }); if (!response.ok) throw new Error("No pudimos subir la imagen."); const result = await response.json() as { secure_url: string; public_id: string }; setForm(current => ({ ...current, imageUrl: result.secure_url, imagePublicId: result.public_id })); toast.success("Imagen lista."); } catch (error) { toast.error(error instanceof Error ? error.message : "No pudimos subir la imagen."); } finally { setUploading(false); } };
  return <div className="dialog-backdrop"><form className="product-dialog" onSubmit={e => { e.preventDefault(); create.mutate(); }}><header><div><p className="eyebrow">NUEVO PRODUCTO</p><h2>Agrega un plato al menú</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></header><div className="product-form-grid"><label className="upload-zone">{form.imageUrl ? <img src={form.imageUrl} alt="Vista previa"/> : <><UploadCloud/><strong>{uploading ? "Subiendo..." : "Arrastra o selecciona una foto"}</strong><span>JPG, PNG o WebP</span></>}<input type="file" accept="image/*" disabled={uploading} onChange={e => e.target.files?.[0] && void upload(e.target.files[0])}/></label><div className="form-fields"><label>Nombre<Input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Ej. Lomo saltado" required/></label><label>Descripción<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Descripción breve y apetecible"/></label><div className="two-fields"><label>Precio (S/)<Input type="number" min="0.1" step="0.1" value={form.price} onChange={e => setForm({ ...form, price: Number(e.target.value) })} required/></label><label>Costo (S/)<Input type="number" min="0" step="0.1" value={form.cost} onChange={e => setForm({ ...form, cost: Number(e.target.value) })}/></label></div><div className="two-fields"><label>Categoría<select value={form.categoryId} onChange={e => setForm({ ...form, categoryId: e.target.value })}>{data.categories.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Estación<select value={form.stationId} onChange={e => setForm({ ...form, stationId: e.target.value })}>{data.stations.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><label>Tiempo estimado (min)<Input type="number" min="1" value={form.estimatedMinutes} onChange={e => setForm({ ...form, estimatedMinutes: Number(e.target.value) })}/></label></div></div><footer><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" loading={create.isPending}><ImagePlus/> Crear producto</Button></footer></form></div>;
}
