"use client";

import { useQuery } from "@tanstack/react-query";
import { BarChart3, CalendarDays, CircleDollarSign, CreditCard, Download, ReceiptText, TrendingUp, Utensils } from "lucide-react";
import { api, money, shortTime } from "@/lib/client-api";
import { Badge, Button, EmptyState, PageHeader, Skeleton } from "@/components/ui";

type Report = { total: number; count: number; average: number; daily: Array<{ date: string; total: number }>; payments: Array<{ method: string; _sum: { amount: string } }>; items: Array<{ productName: string; _sum: { quantity: number; total: string } }>; sales: Array<{ id: string; total: string; createdAt: string; order: { number: number; waiter?: { firstName: string } | null }; payments: Array<{ method: string }> }> };
export default function ReportsPage() {
  const { data, isLoading } = useQuery({ queryKey: ["reports"], queryFn: () => api<Report>("/api/reports") });
  if (isLoading || !data) return <div><PageHeader title="Reportes"/><Skeleton className="h-[560px] rounded-3xl"/></div>;
  const maxDaily = Math.max(...data.daily.map(day => day.total), 1); const maxItem = Math.max(...data.items.map(item => item._sum.quantity), 1);
  return <div className="page-stack"><PageHeader eyebrow="ÚLTIMOS 7 DÍAS" title="Reportes de ventas" description="Decisiones claras a partir de la operación real." action={<div className="report-actions"><Button variant="secondary"><CalendarDays/> Rango</Button><Button variant="secondary" onClick={() => window.print()}><Download/> Exportar</Button></div>}/><section className="report-metrics"><article><CircleDollarSign/><span>VENTAS NETAS</span><strong>{money(data.total)}</strong></article><article><ReceiptText/><span>TRANSACCIONES</span><strong>{data.count}</strong></article><article><TrendingUp/><span>TICKET PROMEDIO</span><strong>{money(data.average)}</strong></article><article><CreditCard/><span>MÉTODO PRINCIPAL</span><strong>{data.payments.sort((a, b) => Number(b._sum.amount) - Number(a._sum.amount))[0]?.method ?? "—"}</strong></article></section><section className="reports-grid"><article className="panel sales-chart"><div className="panel-heading"><div><span>RENDIMIENTO</span><h2>Ventas por día</h2></div><BarChart3/></div>{data.daily.length ? <div className="bar-chart">{data.daily.map(day => <div key={day.date}><strong>{money(day.total)}</strong><i><b style={{ height: `${Math.max(8, (day.total / maxDaily) * 100)}%` }}/></i><span>{new Intl.DateTimeFormat("es-PE", { weekday: "short" }).format(new Date(`${day.date}T12:00:00`))}</span></div>)}</div> : <EmptyState icon={<BarChart3/>} title="Sin ventas en el período" detail="La gráfica se completará con las primeras ventas."/>}</article><article className="panel"><div className="panel-heading"><div><span>TOP PRODUCTOS</span><h2>Lo más vendido</h2></div><Utensils/></div><div className="ranking report-ranking">{data.items.map((item, index) => <div key={item.productName}><span className="rank">{index + 1}</span><div><strong>{item.productName}</strong><i><b style={{ width: `${item._sum.quantity / maxItem * 100}%` }}/></i></div><span>{item._sum.quantity} uds.</span></div>)}</div></article></section><section className="panel sales-table"><div className="panel-heading"><div><span>DETALLE</span><h2>Ventas recientes</h2></div><Badge tone="success">{data.sales.length} registros</Badge></div>{data.sales.map(sale => <div className="sale-row" key={sale.id}><span>#{sale.order.number}</span><div><strong>{sale.order.waiter?.firstName ?? "Equipo"}</strong><small>{shortTime(sale.createdAt)}</small></div><Badge tone="info">{sale.payments.map(p => p.method).join(" + ")}</Badge><strong>{money(sale.total)}</strong></div>)}</section></div>;
}
