"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, UtensilsCrossed } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/client-api";
import { Button, Input } from "@/components/ui";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState("admin@rinconcito.pe"); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { const result = await api<{ role: string }>("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); toast.success("Bienvenido. Todo está listo."); const destination = result.role === "MESERO" ? "/tables" : result.role === "COCINA" ? "/kitchen" : result.role === "CAJERO" ? "/cash" : "/dashboard"; router.replace(destination as never); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "No pudimos iniciar sesión."); } finally { setLoading(false); } };
  return <main className="login-page"><section className="login-story"><div className="story-pattern"/><div className="login-brand"><span><UtensilsCrossed size={22}/></span><div><strong>Rinconcito</strong><small>del Sabor</small></div></div><div className="story-copy"><span className="story-pill"><span/> OPERACIÓN EN TIEMPO REAL</span><h1>Todo tu restaurante,<br/>en perfecta <em>sincronía.</em></h1><p>Salón, cocina y caja conectados para brindar una experiencia extraordinaria.</p><div className="story-stats"><div><strong>−32%</strong><span>Tiempo de atención</span></div><div><strong>0</strong><span>Pedidos olvidados</span></div><div><strong>24/7</strong><span>Control operativo</span></div></div></div><footer><ShieldCheck size={17}/> Conexión segura · Información protegida</footer></section><section className="login-form-wrap"><form onSubmit={submit} className="login-form"><div className="mobile-login-logo"><UtensilsCrossed/><strong>Rinconcito del Sabor</strong></div><p className="eyebrow">BIENVENIDO DE VUELTA</p><h2>Inicia sesión</h2><p>Ingresa tus datos para continuar con tu jornada.</p><label>Correo electrónico<div className="input-icon"><Mail size={18}/><Input value={email} onChange={e => setEmail(e.target.value)} type="email" autoComplete="email" placeholder="tu@restaurante.pe" required/></div></label><label>Contraseña<div className="input-icon"><LockKeyhole size={18}/><Input value={password} onChange={e => setPassword(e.target.value)} type={show ? "text" : "password"} autoComplete="current-password" placeholder="Tu contraseña" required/><button type="button" onClick={() => setShow(v => !v)}>{show ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label><div className="login-options"><label><input type="checkbox"/> Recordarme</label><a href="/forgot-password">¿Olvidaste tu contraseña?</a></div><Button type="submit" loading={loading} className="login-submit">{loading ? "Ingresando..." : "Ingresar al sistema"}</Button><p className="login-help">¿Necesitas ayuda? <a href="mailto:soporte@rinconcito.pe">Contacta a soporte</a></p></form><footer>© 2026 Rinconcito del Sabor · v1.0</footer></section></main>;
}
