"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Mail, Plus, Search, ShieldCheck, UserRound, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/client-api";
import { Badge, Button, Input, PageHeader, Skeleton } from "@/components/ui";
type User = { id: string; email: string; firstName: string; lastName: string; status: "ACTIVE" | "DISABLED" | "LOCKED"; lastLoginAt?: string; roles: Array<{ role: { id: string; name: string } }> }; type Role = { id: string; name: string; description?: string };
export default function UsersPage() { const client = useQueryClient(); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const { data, isLoading } = useQuery({ queryKey: ["users"], queryFn: () => api<{ users: User[]; roles: Role[] }>("/api/users") }); const status = useMutation({ mutationFn: ({ id, value }: { id: string; value: User["status"] }) => api(`/api/users/${id}`, { method: "PATCH", body: JSON.stringify({ status: value }) }), onSuccess: () => { toast.success("Acceso actualizado."); void client.invalidateQueries({ queryKey: ["users"] }); }, onError: error => toast.error(error.message) }); if (isLoading || !data) return <Skeleton className="h-[600px] rounded-3xl"/>; const users = data.users.filter(user => `${user.firstName} ${user.lastName} ${user.email}`.toLowerCase().includes(search.toLowerCase())); return <div className="page-stack"><PageHeader eyebrow="EQUIPO Y ACCESO" title="Usuarios y roles" description="Cada trabajador ve solo las herramientas que necesita." action={<Button onClick={() => setOpen(true)}><Plus/> Nuevo usuario</Button>}/><section className="inventory-summary"><article><span><UsersRound/></span><div><small>USUARIOS</small><strong>{data.users.length}</strong></div></article><article><span className="green"><ShieldCheck/></span><div><small>ACTIVOS</small><strong>{data.users.filter(u => u.status === "ACTIVE").length}</strong></div></article><article><span className="warn"><UserRound/></span><div><small>ROLES</small><strong>{data.roles.length}</strong></div></article></section><div className="search-field inventory-search"><Search/><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar trabajador..."/></div><section className="panel user-list">{users.map(user => <article key={user.id}><div className="user-avatar">{user.firstName[0]}{user.lastName[0]}</div><div><strong>{user.firstName} {user.lastName}</strong><span><Mail/> {user.email}</span></div><Badge tone="info">{user.roles.map(item => item.role.name).join(", ")}</Badge><button className={`user-status ${user.status.toLowerCase()}`} onClick={() => status.mutate({ id: user.id, value: user.status === "ACTIVE" ? "DISABLED" : "ACTIVE" })}><i/>{user.status === "ACTIVE" ? "Activo" : "Desactivado"}</button></article>)}</section>{open && <CreateUser roles={data.roles} onClose={() => setOpen(false)} onCreated={() => { setOpen(false); void client.invalidateQueries({ queryKey: ["users"] }); }}/>}</div>; }
function CreateUser({ roles, onClose, onCreated }: { roles: Role[]; onClose: () => void; onCreated: () => void }) { const [form, setForm] = useState({ firstName: "", lastName: "", email: "", roleId: roles[0]?.id ?? "" }); const mutation = useMutation({ mutationFn: () => api("/api/users", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => { toast.success("Usuario creado. Enviamos el enlace para configurar su contraseña."); onCreated(); }, onError: error => toast.error(error.message) }); return <div className="dialog-backdrop"><form className="small-dialog" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><button className="icon-button dialog-close" type="button" onClick={onClose}><X/></button><p className="eyebrow">NUEVO TRABAJADOR</p><h2>Crear usuario</h2><p>Recibirá un correo seguro para establecer su contraseña.</p><div className="two-fields"><label>Nombres<Input value={form.firstName} onChange={e => setForm({ ...form, firstName: e.target.value })} required/></label><label>Apellidos<Input value={form.lastName} onChange={e => setForm({ ...form, lastName: e.target.value })} required/></label></div><label>Correo<Input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required/></label><label>Rol<select value={form.roleId} onChange={e => setForm({ ...form, roleId: e.target.value })}>{roles.map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><Button type="submit" loading={mutation.isPending}>Crear y enviar acceso</Button></form></div>; }
