import { z } from "zod";
import { handleApiError, ok, readJson } from "@/lib/api";
import { requirePermission } from "@/lib/auth";
import { db } from "@/lib/db";
import { ConflictError } from "@/lib/errors";
import { publishRealtimeEvent } from "@/lib/realtime";
import { recordAudit } from "@/services/audit.service";
const schema = z.object({ action: z.enum(["dispatch", "deliver", "cancel"]) });
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { try { const user = await requirePermission("delivery.manage"); const { id } = await context.params; const { action } = schema.parse(await readJson(request)); const order = await db.$transaction(async tx => { const before = await tx.order.findUniqueOrThrow({ where: { id }, include: { delivery: true } }); if (action === "dispatch") { if (before.status !== "READY" || !before.delivery) throw new ConflictError("El pedido debe estar listo antes de salir a reparto."); await tx.deliveryOrder.update({ where: { orderId: id }, data: { status: "ON_THE_WAY" } }); } else if (action === "deliver") { if (!(["READY", "DELIVERED"] as string[]).includes(before.status)) throw new ConflictError("El pedido aún no está listo."); await tx.order.update({ where: { id }, data: { status: "DELIVERED", deliveredAt: new Date() } }); if (before.delivery) await tx.deliveryOrder.update({ where: { orderId: id }, data: { status: "DELIVERED", deliveredAt: new Date() } }); } else { if (before.status === "PAID") throw new ConflictError("No puedes cancelar un pedido pagado."); await tx.order.update({ where: { id }, data: { status: "CANCELLED", cancelledAt: new Date() } }); if (before.delivery) await tx.deliveryOrder.update({ where: { orderId: id }, data: { status: "CANCELLED" } }); } await recordAudit(tx, { userId: user.id, action: `EXTERNAL_ORDER_${action.toUpperCase()}`, module: "delivery", entity: "Order", entityId: id, before: { status: before.status }, after: { action } }); return tx.order.findUniqueOrThrow({ where: { id }, include: { items: true, delivery: true } }); }); await publishRealtimeEvent({ resource: "orders", action: "status_changed", id }); return ok(order); } catch (error) { return handleApiError(error); } }
