"use client";
/* Public product media uses Cloudinary responsive transformations. */
/* eslint-disable @next/next/no-img-element */
import { useQuery } from "@tanstack/react-query";
import { Clock3, MapPin, Phone, Search, UtensilsCrossed } from "lucide-react";
import { use, useState } from "react";
import { api, money } from "@/lib/client-api";
import { Badge, Input, Skeleton } from "@/components/ui";
type Menu = { settings: { tradeName: string; address?: string; phone?: string; orderingEnabled: boolean }; categories: Array<{ id: string; name: string; products: Array<{ id: string; name: string; description?: string; price: string; imageUrl?: string; estimatedMinutes?: number; availability: string; featured: boolean }> }> };
export default function PublicMenuPage({ params }: { params: Promise<{ number: string }> }) { const { number } = use(params); const [search, setSearch] = useState(""); const { data, isLoading } = useQuery({ queryKey: ["public-menu"], queryFn: () => api<Menu>("/api/public/menu") }); if (isLoading || !data) return <main className="public-menu"><Skeleton className="h-72 rounded-none"/><Skeleton className="m-8 h-96 rounded-3xl"/></main>; return <main className="public-menu"><header><div className="public-brand"><UtensilsCrossed/><strong>{data.settings.tradeName}</strong></div><div><p>SABORES QUE ABRAZAN</p><h1>Nuestra carta</h1><span className="public-table-chip">Mesa {String(number).padStart(2, "0")}</span><span><MapPin/> {data.settings.address}</span><span><Phone/> {data.settings.phone}</span></div></header><section><div className="public-search"><Search/><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="¿Qué se te antoja hoy?"/></div>{data.categories.map(category => { const products = category.products.filter(product => product.name.toLowerCase().includes(search.toLowerCase())); if (!products.length) return null; return <div className="public-category" key={category.id}><div><span>{category.name.toUpperCase()}</span><h2>{category.name}</h2></div><div className="public-products">{products.map(product => <article key={product.id} className={product.availability === "SOLD_OUT" ? "sold-out" : ""}>{product.imageUrl && <img src={product.imageUrl} alt=""/>}<div>{product.featured && <Badge tone="warning">Favorito</Badge>}<h3>{product.name}</h3><p>{product.description}</p><span><Clock3/> {product.estimatedMinutes ?? 10} min</span><footer><strong>{money(product.price)}</strong>{product.availability === "SOLD_OUT" && <Badge tone="danger">Agotado</Badge>}</footer></div></article>)}</div></div>})}</section><footer>Hecho con cariño · {data.settings.tradeName}</footer></main>; }
