"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Check, ChefHat, Clock3, Flame, Maximize, Volume2, VolumeX } from "lucide-react";
import { toast } from "sonner";
import { api, elapsed } from "@/lib/client-api";
import { Badge, Button, EmptyState, Skeleton } from "@/components/ui";
import { cn } from "@/lib/utils";

type Item = { id: string; productName: string; quantity: number; status: string; notes?: string | null; modifiers: Array<{ name: string }>; product: { station?: { id: string; name: string } | null } };
type Order = { id: string; number: number; status: string; priority: string; sentAt: string; openedAt: string; notes?: string | null; table?: { number: number } | null; waiter?: { firstName: string; lastName: string } | null; items: Item[]; tickets: Array<{ station: { id: string; name: string } }> };

function timerLabel(minutes: number, tick: number) { const seconds = Math.floor(tick / 1000) % 60; return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`; }

export default function KitchenPage() {
  const client = useQueryClient(); const [station, setStation] = useState("all"); const [tick, setTick] = useState(0); const [sound, setSound] = useState(true); const previousCount = useRef<number | undefined>(undefined);
  const { data: orders = [], isLoading } = useQuery({ queryKey: ["orders", "kitchen"], queryFn: () => api<Order[]>("/api/orders?view=kitchen") });
  useEffect(() => { const interval = setInterval(() => setTick(Date.now()), 1000); return () => clearInterval(interval); }, []);
  useEffect(() => { if (previousCount.current !== undefined && orders.length > previousCount.current && sound) { const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.connect(gain); gain.connect(context.destination); oscillator.frequency.value = 660; gain.gain.value = 0.08; oscillator.start(); oscillator.stop(context.currentTime + 0.16); } previousCount.current = orders.length; }, [orders.length, sound]);
  const stations = useMemo(() => [...new Map(orders.flatMap(order => order.tickets.map(ticket => [ticket.station.id, ticket.station.name] as const))).entries()], [orders]);
  const filtered = useMemo(() => orders.map(order => ({ ...order, items: station === "all" ? order.items : order.items.filter(item => item.product.station?.id === station) })).filter(order => order.items.length), [orders, station]);
  const mutation = useMutation({ mutationFn: ({ url, body }: { url: string; body?: object }) => api(url, { method: "PATCH", ...(body ? { body: JSON.stringify(body) } : {}) }), onSuccess: () => void client.invalidateQueries({ queryKey: ["orders"] }), onError: error => toast.error(error.message) });
  const markAll = async (order: Order) => { const pending = order.items.filter(item => item.status !== "READY" && item.status !== "DELIVERED"); for (const item of pending) await mutation.mutateAsync({ url: `/api/orders/${order.id}/items/${item.id}/ready` }); toast.success(`Pedido #${order.number} listo para entregar.`); };
  return <main className="kds-page"><header className="kds-header"><div className="kds-brand"><span><ChefHat/></span><div><strong>COCINA</strong><small>Kitchen Display System</small></div></div><div className="kds-summary"><div><span>NUEVAS</span><strong>{orders.filter(o => o.status === "SENT").length}</strong></div><div><span>PREPARANDO</span><strong>{orders.filter(o => ["PREPARING", "PARTIALLY_READY"].includes(o.status)).length}</strong></div><div><span>LISTAS</span><strong>{orders.filter(o => o.status === "READY").length}</strong></div></div><div className="kds-controls"><button onClick={() => setSound(v => !v)}>{sound ? <Volume2/> : <VolumeX/>}</button><button onClick={() => document.documentElement.requestFullscreen?.()}><Maximize/></button><div><Clock3/>{new Intl.DateTimeFormat("es-PE", { hour: "2-digit", minute: "2-digit" }).format(new Date(tick))}</div></div></header><div className="kds-stations"><button className={station === "all" ? "active" : ""} onClick={() => setStation("all")}>Todas <span>{orders.length}</span></button>{stations.map(([id, name]) => <button className={station === id ? "active" : ""} key={id} onClick={() => setStation(id)}>{name}</button>)}<div className="kds-live"><i/> Actualización automática</div></div>
    {isLoading ? <div className="kds-grid">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-[560px] rounded-3xl"/>)}</div> : !filtered.length ? <EmptyState icon={<ChefHat/>} title="Cocina al día" detail="Las nuevas comandas aparecerán aquí automáticamente."/> : <section className="kds-grid">{filtered.map(order => { const minutes = elapsed(order.sentAt); const done = order.items.filter(i => ["READY", "DELIVERED"].includes(i.status)).length; const urgent = minutes >= 20; const warning = minutes >= 10; return <article className={cn("ticket", urgent && "ticket-urgent", warning && !urgent && "ticket-warning", order.status === "READY" && "ticket-ready")} key={order.id}><div className="ticket-priority">{order.priority !== "NORMAL" ? <Badge tone="danger"><Flame/> {order.priority}</Badge> : <span>ORDEN #{order.number}</span>}<span>{order.tickets.map(t => t.station.name).join(" · ")}</span></div><header><div><small>{order.table ? "MESA" : "PEDIDO"}</small><strong>{order.table ? String(order.table.number).padStart(2, "0") : "LLEVAR"}</strong></div><div className="ticket-timer"><Clock3/><strong>{timerLabel(minutes, tick)}</strong><small>{urgent ? "DEMORADO" : warning ? "ATENCIÓN" : "EN TIEMPO"}</small></div></header><div className="ticket-progress"><span><b>{done}</b> de {order.items.length} listos</span><i><b style={{ width: `${(done / order.items.length) * 100}%` }}/></i></div><div className="ticket-items">{order.items.map(item => <button key={item.id} disabled={item.status === "READY" || item.status === "DELIVERED" || order.status === "SENT"} onClick={() => mutation.mutate({ url: `/api/orders/${order.id}/items/${item.id}/ready` })} className={cn(["READY", "DELIVERED"].includes(item.status) && "done")}><span>{item.quantity}×</span><div><strong>{item.productName}</strong>{item.modifiers.map(mod => <small key={mod.name}>• {mod.name}</small>)}{item.notes && <em>{item.notes}</em>}</div><i>{["READY", "DELIVERED"].includes(item.status) ? <Check/> : "LISTO"}</i></button>)}</div><footer><div><span>MESERO</span><strong>{order.waiter?.firstName ?? "Equipo"}</strong></div>{order.status === "SENT" ? <Button loading={mutation.isPending} onClick={() => mutation.mutate({ url: `/api/orders/${order.id}/status`, body: { action: "start" } })}><Flame/> Iniciar preparación</Button> : order.status === "READY" ? <div className="ready-label"><BellRing/> LISTO PARA ENTREGAR</div> : <Button loading={mutation.isPending} onClick={() => void markAll(order)}><Check/> Marcar todo listo</Button>}</footer></article>; })}</section>}
  </main>;
}
