"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Check, ChefHat, ClipboardList, Clock3 } from "lucide-react";
import { toast } from "sonner";
import { api, elapsed, money } from "@/lib/client-api";
import { Badge, Button, EmptyState, Pagination, PageHeader, Skeleton } from "@/components/ui";
type Order = { id: string; number: number; status: string; total: string; sentAt?: string; table?: { number: number; zone: { name: string } } | null; waiter?: { firstName: string } | null; items: Array<{ id: string; productName: string; quantity: number; status: string }> };
export default function OrdersPage() { const client = useQueryClient(); const [page, setPage] = useState(1); const { data = [], isLoading } = useQuery({ queryKey: ["orders", "active"], queryFn: () => api<Order[]>("/api/orders") }); const mutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => api(`/api/orders/${id}/status`, { method: "PATCH", body: JSON.stringify({ action }) }), onSuccess: () => { toast.success("Pedido actualizado."); void client.invalidateQueries({ queryKey: ["orders"] }); }, onError: error => toast.error(error.message) }); if (isLoading) return <Skeleton className="h-[600px] rounded-xl"/>;
  const pageSize = 8;
  const totalPages = Math.max(1, Math.ceil(data.length / pageSize));
  const safePage = Math.min(page, totalPages);
  const visible = data.slice((safePage - 1) * pageSize, safePage * pageSize);
  return <div className="page-stack"><PageHeader eyebrow="SEGUIMIENTO" title="Pedidos activos" description="Desde cocina hasta la entrega, sin perder ningún detalle."/><div className="orders-board">{visible.map(order => <article key={order.id}><header><div><small>{order.table ? `MESA ${String(order.table.number).padStart(2, "0")}` : "PARA LLEVAR"}</small><h3>Pedido #{order.number}</h3></div><Badge tone={order.status === "READY" ? "success" : order.status === "PENDING_PAYMENT" ? "warning" : "info"}>{order.status.replaceAll("_", " ")}</Badge></header><div className="order-meta"><span><Clock3/> {order.sentAt ? `${elapsed(order.sentAt)} min` : "Nuevo"}</span><span><ChefHat/> {order.items.filter(i => i.status === "READY").length}/{order.items.length} listos</span></div><div className="order-products">{order.items.map(item => <span key={item.id} className={item.status === "READY" ? "done" : ""}>{item.quantity}× {item.productName}{item.status === "READY" && <Check/>}</span>)}</div><footer><strong>{money(order.total)}</strong>{order.status === "READY" && <Button onClick={() => mutation.mutate({ id: order.id, action: "deliver" })}><Check/> Entregar</Button>}{order.status === "DELIVERED" && <Button onClick={() => mutation.mutate({ id: order.id, action: "request_bill" })}><BellRing/> Solicitar cuenta</Button>}</footer></article>)}</div><Pagination page={safePage} totalPages={totalPages} totalItems={data.length} pageSize={pageSize} onPageChange={setPage}/>{!data.length && <EmptyState icon={<ClipboardList/>} title="No hay pedidos activos" detail="Los pedidos enviados desde salón aparecerán aquí."/>}</div>; }
